services:
  postgres:
    image: postgres:16-alpine
    container_name: fisioterapia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fisioterapia_db
      POSTGRES_USER: fisioterapia_user
      POSTGRES_PASSWORD: fisioterapia_pass
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
